#!/usr/bin/env python3
"""Generate Redact's pattern-only gitleaks recognizer data.

This intentionally imports only rule identifiers and regular expressions. It
does not import gitleaks allowlists, entropy checks, or API liveness checks.
"""
import json
import tomllib
import urllib.request
from pathlib import Path

URL = "https://raw.githubusercontent.com/gitleaks/gitleaks/master/config/gitleaks.toml"
OUT = Path(__file__).parents[1] / "crates/redact-core/src/recognizers/gitleaks_rules.rs"

with urllib.request.urlopen(URL) as response:
    config = tomllib.loads(response.read().decode())

rules = [
    (rule["id"], rule["regex"])
    for rule in config["rules"]
    if "regex" in rule
]
body = "// Generated by tools/import_gitleaks_rules.py; do not edit manually.\n"
body += "pub const GITLEAKS_RULES: &[(&str, &str)] = &[\n"
body += "".join(f"    ({json.dumps(name)}, {json.dumps(regex)}),\n" for name, regex in rules)
body += "];\n"
OUT.write_text(body)
